
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/abiosoft/caddy-git"

[[constraint]]
  branch = "master"
  name = "github.com/caddyserver/builds"

[[constraint]]
  branch = "master"
  name = "github.com/codahale/aesnicheck"

[[constraint]]
  name = "github.com/dustin/go-humanize"

[[constraint]]
  branch = "master"
  name = "github.com/flynn/go-shlex"

[[constraint]]
  name = "github.com/google/uuid"

[[constraint]]
  name = "github.com/gorilla/websocket"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-syslog"

[[constraint]]
  branch = "master"
  name = "github.com/jimstudt/http-authentication"

[[constraint]]
  name = "github.com/lucas-clemente/quic-go"

[[constraint]]
  name = "github.com/naoina/toml"
  version = "0.1.1"

[[constraint]]
  name = "github.com/russross/blackfriday"

[[constraint]]
  branch = "acmev2"
  name = "github.com/xenolf/lego"

[[constraint]]
  name = "golang.org/x/crypto"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/mcuadros/go-syslog.v2"
  version = "2.2.1"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
